//################# LIBS #####################
import { Metadata } from 'next';
import localFont from 'next/font/local';

//################# STYLES ###################
// import { Golos_Text, Arimo } from 'next/font/google';
import '../styles/globals.css';

const golos = localFont({
  src: [
    { path: '../vendor/fonts/golos-text_demibold.woff2', weight: '600' },
    { path: '../vendor/fonts/golos-text_demibold.woff', weight: '600' },
    { path: '../vendor/fonts/Golos-Text_DemiBold.ttf', weight: '600' },
    { path: '../vendor/fonts/golos-text_medium.woff2', weight: '500' },
    { path: '../vendor/fonts/golos-text_medium.woff', weight: '500' },
    { path: '../vendor/fonts/Golos-Text_Medium.ttf', weight: '500' },
  ],
  // subsets: ['cyrillic', 'latin'],
  // weight: ['500', '600'],
  variable: '--font-family__h',
  display: 'swap',
  fallback: ['Arial', 'Helvetica', 'sans-serif'],
});

const arimo = localFont({
  src: [
    { path: '../vendor/fonts/Arimo-Regular.woff2' },
    { path: '../vendor/fonts/Arimo-Regular.woff' },
    { path: '../vendor/fonts/Arimo-Regular.ttf' },
  ],
  // subsets: ['cyrillic', 'latin'],
  weight: '400',
  variable: '--font-family__p',
  display: 'swap',
  fallback: ['Arial', 'Helvetica', 'sans-serif'],
});

//################ LAYOUT ####################
import Header from '@/components/header/Header';
import Footer from '@/components/footer/Footer';

export const targetBranch = 'Ростов-на-Дону';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ru">
      <body className={golos.variable + ' ' + arimo.variable}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}

//################# META ###################
export const metadata: Metadata = {
  title: 'Стройматериалы оптом | Аквист',
  description:
    'Официальный сайт компании ВИСТ. Оптовые поставки профессиональных строительных и отделочных материалов в Ростов-на-Дону и Ростовской области.Generated by create next app',
  keywords:
    'вист, аквист, компания вист, компания аквист, вист в ростове-на-дону, стройматериалы в Ростове-на-Дону, стройматериалы оптом, строительные материалы',
};
